#!/bin/bash
# boot-blofeld
#
# @Usage: Sets up a simple transparent Squid on a secondary (assumed eth1) network connection.
# @Requires: Squid, DHCP3-Server
# @Author: Matt Carter <m@ttcarter.com>
#
# Code taken from CyberCiti.biz (http://www.cyberciti.biz/tips/linux-setup-transparent-proxy-squid-howto.html) and mangled gracelessly

if [ `whoami` != 'root' ]; then
	echo "You need to be root to do this. Attempting to SUDO self"
	sudo "$0"
	exit
fi

# Where is Squid?
SQUID_SERVER="192.168.1.250"
# Interface connected to Internet
INTERNET="wlan0"
# Interface connected to LAN
LAN_IN="eth0"
# Squid port
SQUID_PORT="3128"

echo "Pushing down $LAN_IN..."
ifconfig "$LAN_IN" down
echo "Bringing up $LAN_IN on $SQUID_SERVER..."
ifconfig "$LAN_IN" up "$SQUID_SERVER"
echo "Rebooting DHCPD..."
/etc/init.d/dhcp3-server restart
 
echo "Setting up IP Routing..."
# Clean old firewall
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
# Load IPTABLES modules for NAT and IP conntrack support
modprobe ip_conntrack
modprobe ip_conntrack_ftp
# For win xp ftp client
#modprobe ip_nat_ftp
echo 1 >/proc/sys/net/ipv4/ip_forward
# Setting default filter policy
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
# Unlimited access to loop back
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
# Allow UDP, DNS and Passive FTP
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Forward DNS
iptables -A INPUT -p tcp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT

# set this system as a router for Rest of LAN
iptables --table nat --append POSTROUTING --out-interface $INTERNET -j MASQUERADE
iptables --append FORWARD --in-interface $LAN_IN -j ACCEPT
# unlimited access to LAN
iptables -A INPUT -i $LAN_IN -j ACCEPT
iptables -A OUTPUT -o $LAN_IN -j ACCEPT

# DNAT port 80 request comming from LAN systems to squid 3128 ($SQUID_PORT) aka transparent proxy
iptables -t nat -A PREROUTING -i $LAN_IN -p tcp -d  $SQUID_SERVER --dport 80 -j ACCEPT
iptables -t nat -A PREROUTING -i $LAN_IN -p tcp --dport 80 -j DNAT --to $SQUID_SERVER:$SQUID_PORT
iptables -t nat -A PREROUTING -i $LAN_IN -p tcp --dport 443 -j DNAT --to $SQUID_SERVER:$SQUID_PORT
# Unlimited access to internet
iptables -A INPUT -i $INTERNET -j ACCEPT
iptables -A OUTPUT -o $INTERNET -j ACCEPT
# DROP everything and Log it
iptables -A INPUT -j LOG
iptables -A INPUT -j DROP

echo "Setting up routing defaults"
echo " * Remove default"
route del default
echo " * Add default gateway"
route add default gw 131.245.176.1 wlan0

echo "Setting up DNS resolution"
echo 'domain lan' >/etc/resolv.conf
echo 'search bondstaff.bond.edu.au' >>/etc/resolv.conf
echo 'nameserver 131.244.1.1' >>/etc/resolv.conf
echo 'nameserver 131.244.1.2' >>/etc/resolv.conf

echo "Done"
